### WARNING ###
# app.yaml and cloudbuild.yaml cannot be in the same folder

# [START app_yaml]
runtime: nodejs10
handlers:
  #App
- url: /api/.*
  script: auto
  # Serve all static files with urls ending with a file extension
- url: /(.*\..+)$ 
  static_files: dist/\1
  upload: dist/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
# [END app_yaml]
